AWSTemplateFormatVersion: '2010-09-09'
Description: Kinesis Firehose for Cowculate sensor network data
Resources:
  DeliveryStream:
    Type: 'AWS::KinesisFirehose::DeliveryStream'
    Properties:
      DeliveryStreamName: cowculate-firehose
      DeliveryStreamType: KinesisStreamAsSource
      KinesisStreamSourceConfiguration:
        KinesisStreamARN:
          Fn::ImportValue: CowculateStreamArn
        RoleARN:
          Fn::Sub: arn:aws:iam::489967615225:role/stream-processing-role
      S3DestinationConfiguration: 
        CloudWatchLoggingOptions: 
          Enabled: true
          LogGroupName: "SensorNetworkData"
          LogStreamName: "S3Delivery"
        BucketARN: 
          Fn::Sub: arn:aws:s3:::cowculate
        BufferingHints:
          IntervalInSeconds: 300
          SizeInMBs: 5
        CompressionFormat: UNCOMPRESSED
        RoleARN:
          Fn::Sub: arn:aws:iam::489967615225:role/stream-processing-role        